services:
  auth-api:
    image: public.ecr.aws/q2n5r5e8/ozrnds/shkedia-photo-gallery-backend:${gallery-backend_VERSION}
    container_name: gallery_backend
    env_file: .local/gallery_backend.env
    environment:
      - JWT_KEY_LOCATION
      - TOKEN_TIME_PERIOD
    expose:
      - "5000"
    ports:
      - "4432:5000"
    volumes:
      - ${HOST_MOUNT}:/temp
    restart: always